name       : xdebug
version    : 3.2.0
release    : 8
source     :
    - https://github.com/xdebug/xdebug/archive/refs/tags/3.2.0.tar.gz : a5979f2060b92375523662f451bfebd76b718116921c60bcdf8e87be0c58dd72
license    : Xdebug-License-1.02
component  : programming.tools
summary    : Xdebug is a debugger and profiler for PHP.
description: |
    Xdebug is a debugger and profiler for PHP.
builddeps  :
    - php-devel
rundeps    :
    - php
setup      : |
    phpize
    aclocal
    autoconf
    %configure --enable-xdebug
build      : |
    %make
install    : |
    install -Dm00644 modules/xdebug.so $installdir/usr/lib64/php/modules/xdebug.so
    install -Dm00644 $pkgfiles/xdebug.ini $installdir/etc/php/conf.d/xdebug.ini
