name       : xdebug
version    : 3.0.2
release    : 7
source     :
    - https://github.com/xdebug/xdebug/archive/3.0.2.tar.gz : 9b1b53468d35dfb3aeabf07c81e6de3b9ab6a7b15f5f5f35af3cac41bd70762c
license    : Xdebug-License-1.02
component  : programming.tools
summary    : Xdebug is a debugger and profiler for PHP.
description: |
    Xdebug is a debugger and profiler for PHP.
builddeps  :
    - php-devel
rundeps    :
    - php
setup      : |
    phpize
    aclocal
    autoconf
    %configure --enable-xdebug
build      : |
    %make
install    : |
    install -Dm00644 modules/xdebug.so $installdir/usr/lib64/php/modules/xdebug.so
    install -Dm00644 $pkgfiles/xdebug.ini $installdir/etc/php/conf.d/xdebug.ini
