name       : xdebug
version    : 2.6.1
release    : 3
source     :
    - https://github.com/xdebug/xdebug/archive/2.6.1.tar.gz : 2fa26dc0cd79ccee96a5f5d180f48942d1a852682d47bf65d19ed8ea4273a249
license    : Xdebug-License-1.01
component  : programming.tools
summary    : Xdebug is a debugger and profiler for PHP.
description: |
    Xdebug is a debugger and profiler for PHP.
builddeps  :
    - php-devel
rundeps    :
    - php
setup      : |
    phpize
    libtoolize --force
    aclocal
    autoconf
    %configure --enable-xdebug
build      : |
    %make
install    : |
    install -Dm00644 modules/xdebug.so $installdir/usr/lib64/php/modules/xdebug.so
    install -Dm00644 $pkgfiles/xdebug.ini $installdir/etc/php/conf.d/xdebug.ini
