name       : xdebug
version    : 2.7.0
release    : 4
source     :
    - https://github.com/xdebug/xdebug/archive/2.7.0.tar.gz : 86df1c16f31a11ed242adbaba7f13290af23ac57e1095a02faceb41ea833f729
license    : Xdebug-License-1.01
component  : programming.tools
summary    : Xdebug is a debugger and profiler for PHP.
description: |
    Xdebug is a debugger and profiler for PHP.
builddeps  :
    - php-devel
rundeps    :
    - php
setup      : |
    phpize
    libtoolize --force
    aclocal
    autoconf
    %configure --enable-xdebug
build      : |
    %make
install    : |
    install -Dm00644 modules/xdebug.so $installdir/usr/lib64/php/modules/xdebug.so
    install -Dm00644 $pkgfiles/xdebug.ini $installdir/etc/php/conf.d/xdebug.ini
